name: Publish Containers

on:
  push:
    tags:
      - "v*"

env:
  GH_TAG: ${{github.ref_name}}

jobs:
  docker-containers:
    name: Build & Publish Containers
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Docker Tags
        # https://github.com/docker/metadata-action
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.actor}}/piko

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: version=$GH_TAG
          file: build/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
